runtime: go112

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /apple-touch-icon\.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon\.png
- url: /.*
  script: auto
  secure: always

includes:
- env.yaml

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
