runtime: go112

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always

includes:
- env.yaml

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
